### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by hdstich**

### CODE REVIEW

**Comment by hdstich** [comment]
@piccobit: 
	This request has been marked as needing help from a contributor.

Please ensure the request meets the requirements listed [here](https://git.k8s.io/community/contributors/devel/help-wanted.md).

If this request no longer meets these requirements, the label can be removed
by commenting with the `/remove-help` command.


<details>

In response to [this](https://github.com/hdstich/prow-test/pull/1):

>/help


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hdstich** [comment]
@piccobit: [cat image](http://thecatapi.com/?id=a0j)

<details>

In response to [this](https://github.com/hdstich/prow-test/pull/1#issuecomment-404745464):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hdstich** [comment]
@piccobit: [dog image](https://random.dog/0fd781ff-ec46-4bdc-a4e8-24f18bf07def.jpg)

<details>

In response to [this](https://github.com/hdstich/prow-test/pull/1#issuecomment-404747124):

>/bark


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hdstich** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/hdstich/prow-test/pull/1#issuecomment-404788837" title="Approved">piccobit</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

If they are not already assigned, you can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/hdstich/prow-test/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hdstich** [comment]
@hdstich: I tried taking some high resolution photos of local farmland, but they all turned out a bit grainy.

<details>

In response to [this](https://github.com/hdstich/prow-test/pull/1#issuecomment-404809412):

>/joke


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by hdstich** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/hdstich/prow-test/pull/1#issuecomment-404814017" title="Approved">asbach</a>*, *<a href="https://github.com/hdstich/prow-test/pull/1#issuecomment-404788837" title="Approved">piccobit</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approvers: 

If they are not already assigned, you can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/hdstich/prow-test/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hdstich** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/hdstich/prow-test/pull/1#issuecomment-404814017" title="Approved">asbach</a>*, *<a href="https://github.com/hdstich/prow-test/pull/1#issuecomment-404821134" title="Approved">piccobit</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/hdstich/prow-test/blob/master/OWNERS)~~ [asbach,piccobit]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by piccobit — APPROVED** [review]

**Pull request merged**
